### ISSUE TITLE
Consider alternate version

### ISSUE THREAD

**Issue by furzeface** [antplant/float-left#2]
This project has potential to be extended. I'd suggest a `float-right`, for a start?

**Comment by JordanRobinson** [comment]
I think that goes against the core values of the project @furzeface.

**Comment by grumpydev22** [comment]
I there is an alternative it should probably be !important too, cos some things really are important

**Comment by antplant** [comment]
You are welcome to start your own project for floating things right but this project is for floating things left.

**Comment by grumpydev22** [comment]
😱

**Comment by furzeface** [comment]
https://github.com/furzeface/float-right 

[Contributors wanted]

**Comment by antplant** [comment]
Nobody floats right anyway.
